language: java
sudo: required
jdk: openjdk8
cache:
  directories:
  - $HOME/.sonar
  - $HOME/.m2
  
addons:
  hosts:
    - api-itest.dcfb.fi
  sonarcloud:
    organization: "metatavu-oy"
          
install: true
  
before_script:
  - scripts/start-keycloak.sh
  - psql -c 'create database dcfbtest' -U postgres
  - psql -c 'create user dcfbtest' -U postgres
  - psql -c "alter user dcfbtest with password 'dcfbtest'"
  - psql -c "alter role dcfbtest with login"
  
script:
  - . travis.sh

notifications:
  email: false
  webhooks:
    - http://travis.metatavu.io:7333/travisping